language: node_js

node_js:
  - 12
  - 14
  - lts/*

branches:
  - master
  - main

install:
  - npm install
  - npm install pm2 -g

stages:
  - Test
  - Build
  - Serve

jobs:
  include:
    - stage: Test
      name: "Server Test"
      script: npm run test
    - stage: Build
      name: "Server Build"
      script: npm run build
    - stage: Serve
      name: "Serve By PM2"
      script: npm run pm2

