name: GraphQL-Explorer-Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  server-job:
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install
          npm install pm2 -g
      - name: Unit Test & Codecov Report
        run: |
          npm run test
          bash <(curl -s https://codecov.io/bash)
      - name: Serve By PM2
        run: npm run pm2
      - name: Delete PM2 Process
        run: pm2 delete all
